// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientService.Infrastructure.Data;

#nullable disable

namespace PatientService.Infrastructure.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20251111093242_UpdateRelationshipRecordAndTestOrder")]
    partial class UpdateRelationshipRecordAndTestOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patient")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IdentifyNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastTestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PatientId");

                    b.ToTable("Patients", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.PatientMedicalRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("RecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMedicalRecords", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.PatientRecordAuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AuditId");

                    b.HasIndex("RecordId");

                    b.ToTable("PatientRecordAuditLogs", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommentId");

                    b.HasIndex("ResultId");

                    b.HasIndex("TestOrderId");

                    b.ToTable("Comment", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.FlaggingSetConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigId"));

                    b.Property<float?>("CriticalThreshold")
                        .HasColumnType("real");

                    b.Property<float?>("HighThreshold")
                        .HasColumnType("real");

                    b.Property<float?>("LowThreshold")
                        .HasColumnType("real");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("1.0");

                    b.HasKey("ConfigId");

                    b.ToTable("FlaggingSetConfig", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestOrder", b =>
                {
                    b.Property<Guid>("TestOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("RunBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RunOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.HasKey("TestOrderId");

                    b.ToTable("TestOrder", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestOrderAuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("text");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.ToTable("TestOrderAuditLog", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Normal");

                    b.Property<string>("InstrumentUsed")
                        .HasColumnType("text");

                    b.Property<string>("Interpretation")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("text");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResultId");

                    b.HasIndex("TestOrderId");

                    b.ToTable("TestResult", "patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.PatientMedicalRecord", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.PatientRecordAuditLog", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient.PatientMedicalRecord", "Record")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.Comment", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.TestOrder.TestResult", "TestResult")
                        .WithMany("Comments")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PatientService.Domain.Entities.TestOrder.TestOrder", "TestOrder")
                        .WithMany("Comments")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestResult", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.TestOrder.TestOrder", "TestOrder")
                        .WithMany("TestResults")
                        .HasForeignKey("TestOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestOrder");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient.PatientMedicalRecord", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestOrder", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.TestOrder.TestResult", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
